openapi: 3.0.3
info:
  description: Read/Write Nature Remo
  title: Nature API
  version: 2.0.0
servers:
  - description: Public API Production
    url: 'https://api.nature.global'
paths:
  /1/appliance_orders:
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Reorder appliances.
        Requires basic.write OAuth2 scopes.
  /1/appliances:
    get:
      security:
        - oauth2:
            - basic.read
      description: |-
        Fetch the list of appliances.
        Requires basic.read OAuth2 scopes.
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Create a new appliance.
        Requires basic.write OAuth2 scopes.
  '/1/appliances/{applianceid}':
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Update an appliance.
        Requires basic.write OAuth2 scopes.
  '/1/appliances/{applianceid}/aircon_settings':
    post:
      security:
        - oauth2:
            - sendir
      description: |-
        Update air conditioner settings.
        Requires sendir OAuth2 scopes.
  '/1/appliances/{applianceid}/delete':
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Delete an appliance.
        Requires basic.write OAuth2 scopes.
  '/1/appliances/{applianceid}/light':
    post:
      security:
        - oauth2:
            - sendir
      description: |-
        Send light signal.
        Requires sendir OAuth2 scopes.
  '/1/appliances/{applianceid}/light_projector':
    post:
      security:
        - oauth2:
            - sendir
      description: |-
        Send light_projector signal.
        Requires sendir OAuth2 scopes.
  '/1/appliances/{applianceid}/signal_orders':
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Reorder signals.
        Requires basic.write OAuth2 scopes.
  '/1/appliances/{applianceid}/signals':
    get:
      security:
        - oauth2:
            - basic.read
      description: |-
        Fetch the list of signals.
        Requires basic.read OAuth2 scopes.
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Create a new signal.
        Requires basic.write OAuth2 scopes.
  '/1/appliances/{applianceid}/tv':
    post:
      security:
        - oauth2:
            - sendir
      description: |-
        Send TV signal.
        Requires sendir OAuth2 scopes.
  /1/detectappliance:
    post:
      security:
        - oauth2:
            - detectappliance
      description: |-
        Find the air conditioner best matching the provided infrared signal.
        Requires detectappliance OAuth2 scopes.
  /1/devices:
    get:
      security:
        - oauth2:
            - basic.read
      description: |-
        Fetch the list of Remo devices.
        Requires basic.read OAuth2 scopes.
  '/1/devices/{deviceid}':
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Update a device.
        Requires basic.write OAuth2 scopes.
  '/1/devices/{deviceid}/appliances':
    get:
      security:
        - oauth2:
            - basic.read
      description: |-
        Fetch the list of appliances registered to the Remo device.
        Requires basic.read OAuth2 scopes.
  '/1/devices/{deviceid}/delete':
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Delete a device.
        Requires basic.write OAuth2 scopes.
  '/1/devices/{deviceid}/humidity_offset':
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Update a device's humidity offset.
        Requires basic.write OAuth2 scopes.
  '/1/devices/{deviceid}/send':
    post:
      security:
        - oauth2:
            - sendrawir
      description: |-
        Send a signal from this device.
        Requires sendrawir OAuth2 scopes.
  '/1/devices/{deviceid}/temperature_offset':
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Update a device's temperature offset.
        Requires basic.write OAuth2 scopes.
  /1/echonetlite/appliances:
    get:
      security:
        - oauth2:
            - basic.read
      description: |-
        Fetch the list of ECHONET Lite appliances.
        Requires basic.read OAuth2 scopes.
  '/1/echonetlite/appliances/{applianceid}/refresh':
    post:
      security:
        - oauth2:
            - echonetlite.*.read
      description: >-
        Notify Remo E / Remo E lite to refresh one or more ECHONET Lite
        properties. This endpoint is subject to ECHONET Lite specific rate
        limiting. See the rate limiting section of the documentation for more
        details.

        Requires echonetlite.*.read OAuth2 scopes.
  '/1/echonetlite/appliances/{applianceid}/set':
    post:
      security:
        - oauth2:
            - echonetlite.*.write
      description: >-
        Set one ECHONET Lite property. This endpoint is subject to ECHONET Lite
        specific rate limiting. See the rate limiting section of the
        documentation for more details.

        Requires echonetlite.*.write OAuth2 scopes.
  /1/homes:
    get:
      security:
        - oauth2:
            - home.read
      description: |-
        Fetch the list of homes.
        Requires home.read OAuth2 scopes.
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Create a new home.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Update a home.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/delete':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Delete a home.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/devices':
    get:
      security:
        - oauth2:
            - home.read
      description: |-
        Fetch the list of devices in a home.
        Requires home.read OAuth2 scopes.
  '/1/homes/{homeid}/invites':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Create a new home invite.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/kick':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Kick a user from a home.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/location':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Update a home's location.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/location/delete':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Delete a home's location.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/location_state/update':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Update the user's location state for a home.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/owner':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Change the owner of the home.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/part':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Part from a home.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/transfer/{tohomeid}':
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Transfer devices to another home.
        Requires home.write OAuth2 scopes.
  '/1/homes/{homeid}/users':
    get:
      security:
        - oauth2:
            - home.read
      description: |-
        Fetch the list of users in a home.
        Requires home.read OAuth2 scopes.
  '/1/invites/{invitetoken}':
    get:
      security:
        - oauth2:
            - home.read
      description: |-
        Show a home invite.
        Requires home.read OAuth2 scopes.
    post:
      security:
        - oauth2:
            - home.write
      description: |-
        Accept a home invite.
        Requires home.write OAuth2 scopes.
  '/1/signals/{signalid}':
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Update a signal.
        Requires basic.write OAuth2 scopes.
  '/1/signals/{signalid}/delete':
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Delete a signal.
        Requires basic.write OAuth2 scopes.
  '/1/signals/{signalid}/send':
    post:
      security:
        - oauth2:
            - sendir
      description: |-
        Send a signal.
        Requires sendir OAuth2 scopes.
  /1/users/me:
    get:
      security:
        - oauth2:
            - basic.read
      description: |-
        Fetch the authenticated user's information.
        Requires basic.read OAuth2 scopes.
    post:
      security:
        - oauth2:
            - basic.write
      description: |-
        Update authenticated user's information.
        Requires basic.write OAuth2 scopes.
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.nature.global/oauth2/auth'
          scopes:
            basic: >-
              Read + write access to user's profile (excluding email), Remos,
              appliances, signals.
            basic.read: >-
              Read only access to user's profile (excluding email), Remos,
              appliances, signals.
            detectappliance: Detect air conditioner model from infrared signals.
            home: Read + write access to user's home.
            home.read: Read only access to user's home.
            sendir: Send infrared signals through Remo.
            sendrawir: Send infrared signals in raw format through Remo.
          tokenUrl: 'https://api.nature.global/oauth2/token'
      type: oauth2

